version: '3.1'

services:

  llamaxing:
    image: quay.io/johannestang/llamaxing:latest
    restart: always
    environment:
      - AUTH_METHOD=jwt
      - IDENTITY_STORE=json
      - AUTH_METHOD_JWT_VERIFY_SIGNATURE=true
      - DEBUG_LEVEL=3
    env_file:
      - .env
    volumes:
      - ${PWD}/../models-$PROVIDER.json:/app/llamaxing/models.json
      - ${PWD}/identities.json:/app/llamaxing/identities.json

  oauth2proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    restart: always
    ports:
     - "4180:4180"
    env_file:
      - .env
    environment:
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_UPSTREAMS=http://llamaxing:8000
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
      - OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
