version: '3.1'

services:

  llamaxing:
    image: quay.io/johannestang/llamaxing:latest
    restart: always
    environment:
      - AUTH_METHOD=jwt
      - IDENTITY_STORE=json
      - AUTH_METHOD_JWT_VERIFY_SIGNATURE=true
      - LOGGING_CLIENT=mongodb
      - LOGGING_CLIENT_MONGODB_URI=mongodb://admin:password@mongo:27017
      - OBSERVABILITY_CLIENT_LANGFUSE_HOST=http://langfuse:3000
      - DEBUG_LEVEL=3
    env_file:
      - .env
    volumes:
      - ${PWD}/../models-$PROVIDER.json:/app/llamaxing/models.json
      - ${PWD}/identities.json:/app/llamaxing/identities.json

  sidecar:
    image: quay.io/johannestang/llamaxing:latest
    restart: always
    ports:
     - "8000:8000"
    environment:
      - APP_MODE=sidecar
      - SIDECAR_AUTH_METHOD=azure
      - SIDECAR_UPSTREAM_URL=http://llamaxing:8000
      - DEBUG_LEVEL=3
    env_file:
      - .env

  mongo:
    image: mongo:6
    restart: always
    ports:
     - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  langfuse:
    image: ghcr.io/langfuse/langfuse:2.3.0
    restart: always
    depends_on:
      - langfuse-db
    ports:
      - "3000:3000"
    env_file:
      - .env      
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@langfuse-db:5432/postgres
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=false
      - NEXT_PUBLIC_SIGN_UP_DISABLED=false
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false
      - HOSTNAME=0.0.0.0
      - AUTH_DISABLE_USERNAME_PASSWORD=true

  langfuse-db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - langfuse_database_data:/var/lib/postgresql/data

  oauth2proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    restart: always
    ports:
     - "4180:4180"
    env_file:
      - .env
    environment:
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_UPSTREAMS=http://llamaxing:8000
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
      - OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_EMAIL_DOMAINS=*

volumes:
  langfuse_database_data:
    driver: local
  mongo_data:
    driver: local
